// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/is_ready_version.test.ts.

/** The version of the `@tssuite/is-ready` package. */
export const isReadyVersion = '0.0.3';
